<?php

function test_pedro_menu() {
  $items = array();

  $items['test_pedro/test_pedro'] = array( 
    'title' => 'Test de Pedro', 
    'description' => 'Un módulo de prueba',
    'page callback' => 'drupal_get_form', 
    'page arguments' => array('test_pedro_form'), 
    'access callback' => 'user_is_logged_in',
	'type' => MENU_NORMAL_ITEM
  );

  return $items;
}

function test_pedro_form($form, &$form_state) {
  
  $form['submit_button'] = array(
    '#type' => 'submit',
    '#value' => t('Ir a bienvenida'),
  );

  $form['#submit'][] = 'test_pedro_form_submit';
  
  return $form;
}


function test_pedro_form_submit($form, &$form_state) {
	drupal_goto('nombre_usuario/nombre_usuario');
}
